Bekmurod
Online-Java/lib-version pull request #1
Opened 2023-08-13 23:16 UTC by BekjoN2003

Lib version ga TokenResponse va UserDto class lari qo'shildi

2023-09-05 01:08 UTC, Axmadjanovich requested changes

2023-09-05 01:08 UTC, Axmadjanovich commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-security:2.4.0'
Agar dependency ishlatilmasa, qo'shish kerak emas

2023-09-05 01:10 UTC, Axmadjanovich requested changes

2023-09-05 01:10 UTC, Axmadjanovich commented on build.gradle
> +	implementation 'org.projectlombok:lombok:1.18.26'
lombok oldin bor edi

2023-09-05 01:10 UTC, Axmadjanovich commented on build.gradle
> +	implementation 'io.jsonwebtoken:jjwt-jackson:0.11.2'
JWT kerak bo'lmasa olib tashlash kerak

2023-09-11 09:16 UTC, BekjoN2003 commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-security:2.4.0'
muammo hal qilindi

2023-09-11 09:19 UTC, BekjoN2003 commented on build.gradle
> +	implementation 'io.jsonwebtoken:jjwt-jackson:0.11.2'
bu dependecy UserDetails ni qo'shish uchun kerak

2023-09-11 09:28 UTC, merged